#!/bin/bash

cd ~
git clone https://github.com/AllenInstitute/neuroanalysis
cd neuroanalysis
python setup.py develop

cd ~
git clone https://github.com/AllenInstitute/aisynphys
cd aisynphys
python setup.py develop

#python util/database.py --db-version=synphys_r1.0_2019-08-29_small.sqlite
mkdir -p ~ai_synphys_cache/database
cd ~ai_synphys_cache/database
wget http://campagnola-test-bucket.s3.amazonaws.com/synphys_current_medium.sqlite -O synphys_r1.0_2019-08-29_medium.sqlite
